{
 "title": "Olympus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Methods Last 1h",
   "type": "timeseries",
   "description": "This query shows the increase in the number of requests for each HTTP method over the past hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_methods{job=\"nodejs\"}[1h])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Over 1 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(total_http_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Rate Over 1 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(total_http_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}