export enum EVideoType {
  SETUP = "SETUP",
  SAFETY = "SAFETY",
  WEIGHT_ADJUSTMENT_MANUAL = "WEIGHT_ADJUSTMENT_MANUAL",
  WEIGHT_ADJUSTMENT_LEFT_GRIP = "WEIGHT_ADJUSTMENT_LEFT_GRIP",
  WEIGHT_ADJUSTMENT_RIGHT_GRIP = "WEIGHT_ADJUSTMENT_RIGHT_GRIP"
}
