import {
  DEFAULT_API_AWS_REGION,
  DEFAULT_API_AWS_SECRET,
  DEFAULT_API_BCRYPT_SALT_ROUNDS,
  DEFAULT_API_EMAIL_CONFIRMATION_EXPIRATION_TIME,
  DEFAULT_API_EMAIL_DOMAIN_NAME,
  DEFAULT_API_EMAIL_HOST,
  DEFAULT_API_EMAIL_PASSWORD,
  DEFAULT_API_EMAIL_PORT,
  DEFAULT_API_EMAIL_USERNAME,
  DEFAULT_API_FIRMWARE_MIME_TYPES,
  DEFAULT_API_IMAGE_MIME_TYPES,
  DEFAULT_API_JWT_ACCESS_TOKEN_EXPIRATION_TIME,
  DEFAULT_API_JWT_ACCESS_TOKEN_SECRET,
  DEFAULT_API_JWT_REFRESH_TOKEN_EXPIRATION_TIME,
  DEFAULT_API_JWT_REFRESH_TOKEN_SECRET,
  DEFAULT_API_MAX_FILE_SIZE_MB,
  DEFAULT_API_PORT,
  DEFAULT_API_POSTGRES_DB,
  DEFAULT_API_POSTGRES_HOST,
  DEFAULT_API_POSTGRES_PASSWORD,
  DEFAULT_API_POSTGRES_PORT,
  DEFAULT_API_POSTGRES_USER,
  DEFAULT_API_PREFIX,
  DEFAULT_API_REDIS_HOST,
  DEFAULT_API_REDIS_PORT,
  DEFAULT_API_S3_BUCKET_NAME,
  DEFAULT_API_URL,
  DEFAULT_API_VIDEO_MIME_TYPES,
  DEFAULT_TRANSACTION_SECRET,
  DEFAULT_FRONT_END_URL,
  NUMBER_BYTES_IN_KILOBYTE,
  NUMBER_OF_HOURS_IN_DAY,
  NUMBER_OF_MINUTES_IN_HOUR,
  DEFAULT_AWS_SQS_INTERVAL_TIME_MIN
} from "../constants";
import { EEnvironment } from "../enums";

export const APP_PORT: string | number = process.env.PORT ?? DEFAULT_API_PORT;
export const APP_URL: string = process.env.APP_URL ?? DEFAULT_API_URL;
export const FRONT_END_URL: string = process.env.FRONT_END_URL ?? DEFAULT_FRONT_END_URL;
export const GLOBAL_PREFIX: string = process.env.GLOBAL_PREFIX ?? DEFAULT_API_PREFIX;
export const MAX_FILE_SIZE_MB: number =
  parseInt(process.env.MAX_FILE_SIZE_MB || DEFAULT_API_MAX_FILE_SIZE_MB) *
  NUMBER_BYTES_IN_KILOBYTE *
  NUMBER_BYTES_IN_KILOBYTE;
export const ALLOWED_IMAGE_MIME_TYPES: string[] = (
  process.env.ALLOWED_IMAGE_MIME_TYPES ?? DEFAULT_API_IMAGE_MIME_TYPES
).split(",");
export const ALLOWED_VIDEO_MIME_TYPES: string = process.env.ALLOWED_VIDEO_MIME_TYPES ?? DEFAULT_API_VIDEO_MIME_TYPES;
export const ALLOWED_FIRMWARE_MIME_TYPES: string[] = (
  process.env.ALLOWED_FIRMWARE_MIME_TYPES ?? DEFAULT_API_FIRMWARE_MIME_TYPES
).split(",");
export const JWT_ACCESS_TOKEN_SECRET: string =
  process.env.JWT_ACCESS_TOKEN_SECRET ?? DEFAULT_API_JWT_ACCESS_TOKEN_SECRET;
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME: number =
  parseInt(process.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME || DEFAULT_API_JWT_ACCESS_TOKEN_EXPIRATION_TIME) *
  NUMBER_OF_MINUTES_IN_HOUR;
export const JWT_REFRESH_TOKEN_SECRET: string =
  process.env.JWT_REFRESH_TOKEN_SECRET ?? DEFAULT_API_JWT_REFRESH_TOKEN_SECRET;
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME: number =
  parseInt(process.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME || DEFAULT_API_JWT_REFRESH_TOKEN_EXPIRATION_TIME) *
  NUMBER_OF_HOURS_IN_DAY *
  NUMBER_OF_MINUTES_IN_HOUR *
  NUMBER_OF_MINUTES_IN_HOUR;
export const BCRYPT_SALT_ROUNDS: number = parseInt(process.env.BCRYPT_SALT_ROUNDS || DEFAULT_API_BCRYPT_SALT_ROUNDS);
export const EMAIL_HOST: string = process.env.EMAIL_HOST ?? DEFAULT_API_EMAIL_HOST;
export const EMAIL_PORT: number = parseInt(process.env.EMAIL_PORT || DEFAULT_API_EMAIL_PORT);
export const EMAIL_DOMAIN_NAME: string = process.env.EMAIL_DOMAIN_NAME || DEFAULT_API_EMAIL_DOMAIN_NAME;
export const EMAIL_USERNAME: string = process.env.EMAIL_USERNAME ?? DEFAULT_API_EMAIL_USERNAME;
export const EMAIL_PASSWORD: string = process.env.EMAIL_PASSWORD ?? DEFAULT_API_EMAIL_PASSWORD;
export const EMAIL_CONFIRMATION_EXPIRATION_TIME: number =
  parseInt(process.env.EMAIL_CONFIRMATION_EXPIRATION_TIME || DEFAULT_API_EMAIL_CONFIRMATION_EXPIRATION_TIME) *
  NUMBER_OF_MINUTES_IN_HOUR;
export const AWS_ACCESS_KEY_ID: string = process.env.AWS_ACCESS_KEY_ID ?? DEFAULT_API_AWS_SECRET;
export const AWS_SECRET_ACCESS_KEY: string = process.env.AWS_SECRET_ACCESS_KEY ?? DEFAULT_API_AWS_SECRET;
export const AWS_REGION: string = process.env.AWS_REGION ?? DEFAULT_API_AWS_REGION;
export const S3_BUCKET_NAME: string = process.env.S3_BUCKET_NAME ?? DEFAULT_API_S3_BUCKET_NAME;
export const ENVIRONMENT: EEnvironment = (process.env.ENVIRONMENT as EEnvironment) ?? EEnvironment.PRODUCTION;
export const POSTGRES_PORT: string | number = process.env.POSTGRES_PORT ?? DEFAULT_API_POSTGRES_PORT;
export const POSTGRES_USER: string = process.env.POSTGRES_USER ?? DEFAULT_API_POSTGRES_USER;
export const POSTGRES_HOST: string = process.env.POSTGRES_HOST ?? DEFAULT_API_POSTGRES_HOST;
export const POSTGRES_PASSWORD: string = process.env.POSTGRES_PASSWORD ?? DEFAULT_API_POSTGRES_PASSWORD;
export const POSTGRES_DB: string = process.env.POSTGRES_DB ?? DEFAULT_API_POSTGRES_DB;
export const REDIS_URL: string = `${process.env.REDIS_URL_START || "redis://"}${
  process.env.REDIS_HOST || DEFAULT_API_REDIS_HOST
}:${process.env.REDIS_PORT || DEFAULT_API_REDIS_PORT}`;
export const TRANSACTION_SECRET: string = process.env.TRANSACTION_SECRET ?? DEFAULT_TRANSACTION_SECRET;
export const AWS_SQS_QUEUE_URL: string = process.env.AWS_SQS_QUEUE_URL ?? "";
export const AWS_SQS_INTERVAL_TIME_MIN: number = parseInt(
  process.env.AWS_SQS_INTERVAL_TIME_MIN || DEFAULT_AWS_SQS_INTERVAL_TIME_MIN
);
export const APPLE_BUNDLE_ID: string = process.env.APPLE_BUNDLE_ID ?? "";
