export enum EMetricType {
  TOTAL_STRAIN = "TOTAL_STRAIN",
  TOTAL_MAX_STRAIN = "TOTAL_MAX_STRAIN",
  TOTAL_AVG_MAX_STRAIN = "TOTAL_AVG_MAX_STRAIN",
  TOTAL_COMPLETED_QUANTITY = "TOTAL_COMPLETED_QUANTITY",
  TOTAL_CALORIES_BURNED = "TOTAL_CALORIES_BURNED",
  TOTAL_DURATION = "TOTAL_DURATION",
  CREATED_DATE = "CREATED_DATE"
}
